### ISSUE TITLE
Broken switches in an-anime-game-launcher

### ISSUE THREAD

**Issue by Albert753258** [an-anime-team/gentoo-ebuilds#20]
![image](https://github.com/an-anime-team/gentoo-ebuilds/assets/56261876/5170a07e-0629-480d-9fa7-d996418368d2)
Some toomblers are bllue, but shown as disabled

**Comment by Mar0xy** [comment]
This is not launcher-related nor package-related as this is just a genuine bug with libadwaita and the way the UI gets handled.
