### ISSUE TITLE
Generate missing manifests of the-honkers-railway-launcher-1.2.2-r1.ebuild and an-anime-game-launcher-3.7.4-r1.ebuild

### ISSUE THREAD

**Issue by sifiro** [an-anime-team/gentoo-ebuilds#24]
Hi, emerge/portage is complaining about the missing manifest (I fixed it locally, But someone should fix it!)

**Comment by Schievel1** [comment]
I will fix this once my computer is running again. Unfortunately the ssd broke down.

Or maybe someone else wants to do a quick PR?
