### ISSUE TITLE
the-honkers-railway-launcher gtk version not specified

### ISSUE THREAD

**Issue by jabuxas** [an-anime-team/gentoo-ebuilds#38]
latest stable is 4.10.5 but hrl requires >=4.11, it'd be nice to have that specified in the ebuild

**Comment by Schievel1** [comment]
Yes I just noticed that as well. I specify it in 1.5.1

**Comment by Schievel1** [comment]
Besides, do you know of any good way to check what version of a library dependencies of a package depend on?

**Comment by jabuxas** [comment]
Not really, usually the package creator says those, but if not, you just test those. But i'm pretty sure there should be a better way
