### ISSUE TITLE
Aagl 3.10.2 release

### ISSUE THREAD

**Issue by Schievel1** [an-anime-team/gentoo-ebuilds#57]
As I am currently in vacation without gentoo and even without a laptop, I would kindly ask if someone else could do a PR for 3.10.2 instead. Please test it thoroughly, because I can not and I will blindly merge the PR.

@JohnTheCoolingFan maybe?

**Comment by JohnTheCoolingFan** [comment]
Working on it. I don't have enough space to install the game (already have two others) so my testing won't be completely thorough. Will do as much as I can.

**Comment by Schievel1** [comment]
Thanks. This is just a minor update, so I think as long as the launcher starts our deed is done.
