### ISSUE TITLE
[Solved] Launchers don't compile with link time optimisations

### ISSUE THREAD

**Issue by caemputer** [an-anime-team/gentoo-ebuilds#6]
Could potentially be an issue with my CFLAGS
`/usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: /lib64/libbz2.so.1: error adding symbols: DSO missing from command line` 

Emerge info: https://notebin.de/?0080ddd14cd273b0#FwKDRje3BE2kbZLgJfGDumicRPaimcBW2kXHn1kTXkkg
Complete build log: https://notebin.de/?72a8a35d8c4e8488#FhtwKDzpFEnNs6yi3ThaSBvgpuam9BoENXx77Zsw1eVc

Compilation works correctly when cloning the launcher and compiling manually from the git repo.

**Comment by Schievel1** [comment]
Hm do you have libbz2 on your system? I guess gentoos cargo eclass makes it so that system
Libraries are used instead of downloading the libs. Maybe that's why compilation works for you when doing it without portage. 

Maybe I missed a dependency here.
